//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 10:04:34 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vlsu.ru/inspection", xmlns = {
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://vlsu.ru/inspection", prefix = ""),
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://vlsu.ru/schema/inspection", prefix = "")
})
package ru.vlsu.gibdd.webservice.inspection.io;
