//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.11 at 01:42:45 AM MSK 
//


package ru.vlsu.gibdd.webservice.register.io;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.vlsu.gibdd.webservice.register.io package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.vlsu.gibdd.webservice.register.io
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OwnerIo }
     * 
     */
    public OwnerIo createOwnerIo() {
        return new OwnerIo();
    }

    /**
     * Create an instance of {@link FindRegistrationCertificateResponseIo }
     * 
     */
    public FindRegistrationCertificateResponseIo createFindRegistrationCertificateResponseIo() {
        return new FindRegistrationCertificateResponseIo();
    }

    /**
     * Create an instance of {@link RegistrationCertificateIo }
     * 
     */
    public RegistrationCertificateIo createRegistrationCertificateIo() {
        return new RegistrationCertificateIo();
    }

    /**
     * Create an instance of {@link RegisterVehicleResponseIo }
     * 
     */
    public RegisterVehicleResponseIo createRegisterVehicleResponseIo() {
        return new RegisterVehicleResponseIo();
    }

    /**
     * Create an instance of {@link RegisterVehicleRequestIo }
     * 
     */
    public RegisterVehicleRequestIo createRegisterVehicleRequestIo() {
        return new RegisterVehicleRequestIo();
    }

    /**
     * Create an instance of {@link FindRegistrationCertificateRequestIo }
     * 
     */
    public FindRegistrationCertificateRequestIo createFindRegistrationCertificateRequestIo() {
        return new FindRegistrationCertificateRequestIo();
    }

}
