//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.11 at 01:42:45 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vlsu.ru/registervehicle",  xmlns = {
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://vlsu.ru/schema/owner", prefix = ""),
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://vlsu.ru/registervehicle", prefix = ""),
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://vlsu.ru/schema/registration", prefix = "")
})
package ru.vlsu.gibdd.webservice.register.io;