create table Citizen (
  id bigint generated by default as identity,
  birthPlace varchar(255) not null,
  birthday date not null,
  firstname varchar(255) not null,
  gender varchar(255) not null,
  lastname varchar(255) not null,
  middlename varchar(255),
  issueDate date not null,
  issuedBy varchar(255) not null,
  number varchar(255) not null,
  address varchar(255) not null,
  city varchar(255) not null,
  date date not null,
  district varchar(255),
  region varchar(255) not null,
  series varchar(255) not null,
  primary key (id)
);

create table Owner (
  id bigint generated by default as identity,
  address varchar(255) not null,
  city varchar(255) not null,
  district varchar(255),
  firstname varchar(255) not null,
  lastname varchar(255) not null,
  middlename varchar(255),
  region varchar(255) not null,
  primary key (id)
);

create table RegistrationCertificate (
  id bigint generated by default as identity,
  issueDate date not null,
  issuePlace varchar(255) not null,
  registrationNumber varchar(255) not null,
  owner_id bigint not null,
  vehicle_id bigint not null,
  primary key (id)
);

create table VehiclePass (
  id bigint generated by default as identity,
  bodyColor varchar(255) not null,
  bodyNumber varchar(255),
  builtYear integer not null,
  category varchar(255) not null,
  chassisNumber varchar(255) not null,
  engineNumber varchar(255) not null,
  model varchar(255) not null,
  type varchar(255) not null,
  vin varchar(255) not null,
  primary key (id)
);

alter table Citizen
  add constraint UK6sat5p0fci5gnxc2ha40637b3 unique (series, number);

alter table RegistrationCertificate
  add constraint UK_r6osicgljujoodbmvt05l7ky4 unique (vehicle_id);

alter table RegistrationCertificate
  add constraint UK_5qf94wxouyiev52k84danvd6h unique (registrationNumber);

alter table VehiclePass
  add constraint UK_ld3vtmcjc5fmoj1i7rx70oybc unique (vin);

alter table RegistrationCertificate
  add constraint FK2n2b3kgcsh2ac1jeukdsfxrlk
  foreign key (owner_id)
  references Owner;

alter table RegistrationCertificate
  add constraint FK7yr4rnqigkhts114mw31jnw1c
  foreign key (vehicle_id)
  references VehiclePass;