create table my_citizen (
  id bigint generated by default as identity,
  birthday date not null,
  birthplace varchar(255) not null,
  firstname varchar(255) not null,
  gender varchar(255) not null,
  lastname varchar(255) not null,
  middlename varchar(255),
  issuedate date not null,
  issuedby varchar(255) not null,
  number varchar(255) not null,
  address varchar(255) not null,
  city varchar(255) not null,
  date date not null,
  district varchar(255),
  region varchar(255) not null,
  series varchar(255) not null,
  primary key (id)
);

create table my_citizenblacklist (
  id bigint generated by default as identity,
  statusmessage varchar(255) not null,
  citizen_id bigint not null,
  primary key (id)
);

create table my_vehicleblacklist (
  id bigint generated by default as identity,
  statusmessage varchar(255) not null,
  vehiclepass_id bigint not null,
  primary key (id)
);

create table my_vehiclepass (
  id bigint generated by default as identity,
  bodycolor varchar(255) not null,
  bodynumber varchar(255),
  builtyear integer not null,
  category varchar(255) not null,
  chassisnumber varchar(255) not null,
  enginenumber varchar(255) not null,
  model varchar(255) not null,
  type varchar(255) not null,
  vin varchar(255) not null,
  primary key (id)
);

alter table my_citizen
add constraint UK7e8f2ddi5jdfp5jkcydpfm8ph unique (series, number);

alter table my_vehiclepass
add constraint UK_mwoq6t8tjtn5ywmhtexyu2who unique (vin);

alter table my_citizenblacklist
add constraint FK4l5jehwq557lk4nvgjxo1hhco
foreign key (citizen_id)
references my_citizen;

alter table my_vehicleblacklist
add constraint FK89f29hegyqy0uag7j1gk2o9iw
foreign key (vehiclepass_id)
references my_vehiclepass;

insert into my_citizen(id, firstname, middlename, lastname, gender, birthday, birthplace,
                       series, number, issuedate, issuedby, region, district, city, address, date)
    values(111, 'First1', 'Middle1', 'Last1', 'male', '1991-2-2', 'Place1',
           '1111', '111111', '2011-2-2', 'Place1', 'Region1', 'District1', 'City1', 'Address1', '2001-2-2');

insert into my_vehiclepass(id, vin, model, type, category, enginenumber,
                           chassisnumber, builtyear, bodynumber, bodycolor)
    values(111, 'ABCDEFG1234567890', 'Test', 'Test', 'A', 'ENumber',
           'CNumber', 1981, 'BNumber', 'Red');

insert into my_citizenblacklist(statusmessage, citizen_id) values('Terrorist!', 111);

insert into my_citizenblacklist(statusmessage, citizen_id) values('Gangster!', 111);

insert into my_vehicleblacklist(statusmessage, vehiclepass_id) values('Stolen', 111);