create table Citizen (
  id bigint generated by default as identity,
  birthPlace varchar(255) not null,
  birthday date not null,
  firstname varchar(255) not null,
  gender varchar(255) not null,
  lastname varchar(255) not null,
  middlename varchar(255),
  issueDate date not null,
  issuedBy varchar(255) not null,
  number varchar(255) not null,
  address varchar(255) not null,
  city varchar(255) not null,
  date date not null,
  district varchar(255),
  region varchar(255) not null,
  series varchar(255) not null,
  primary key (id)
);

create table CitizenBlackList (
  id bigint generated by default as identity,
  statusMessage varchar(255) not null,
  record_id bigint not null,
  primary key (id)
);

create table VehicleBlackList (
  id bigint generated by default as identity,
  statusMessage varchar(255) not null,
  record_id bigint not null,
  primary key (id)
);

create table VehiclePass (
  id bigint generated by default as identity,
  bodyColor varchar(255) not null,
  bodyNumber varchar(255),
  builtYear integer not null,
  category varchar(255) not null,
  chassisNumber varchar(255) not null,
  engineNumber varchar(255) not null,
  model varchar(255) not null,
  type varchar(255) not null,
  vin varchar(255) not null,
  primary key (id)
);

alter table Citizen
  add constraint UK6sat5p0fci5gnxc2ha40637b3 unique (series, number);

alter table VehiclePass
  add constraint UK_ld3vtmcjc5fmoj1i7rx70oybc unique (vin);

alter table CitizenBlackList
  add constraint FKip2mqwgbbs0feknjxvbek0ohb
  foreign key (record_id)
  references Citizen;

alter table VehicleBlackList
  add constraint FK8efvfg2x70bdo5jjiisf5b6vv
  foreign key (record_id)
  references VehiclePass;

insert into Citizen(id, firstname, middlename, lastname, gender, birthday, birthplace,
                       series, number, issuedate, issuedby, region, district, city, address, date)
    values(111, 'First1', 'Middle1', 'Last1', 'male', '1991-2-2', 'Place1',
           '1111', '111111', '2011-2-2', 'Place1', 'Region1', 'District1', 'City1', 'Address1', '2001-2-2');

insert into Vehiclepass(id, vin, model, type, category, enginenumber,
                           chassisnumber, builtyear, bodynumber, bodycolor)
    values(111, 'ABCDEFG1234567890', 'Test', 'Test', 'A', 'ENumber',
           'CNumber', 1981, 'BNumber', 'Red');

insert into Citizenblacklist(statusmessage, record_id) values('Terrorist!', 111);

insert into Citizenblacklist(statusmessage, record_id) values('Gangster!', 111);

insert into Vehicleblacklist(statusmessage, record_id) values('Stolen', 111);