//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 01:36:55 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vlsu.ru/blacklistcheck", xmlns = {
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://vlsu.ru/blacklistcheck", prefix = "")
})
package ru.vlsu.gibdd.webservice.blacklist.io;
