create table Citizen (
  id bigint generated by default as identity,
  birthPlace varchar(255) not null,
  birthday date not null,
  firstname varchar(255) not null,
  gender varchar(255) not null,
  lastname varchar(255) not null,
  middlename varchar(255),
  issueDate date not null,
  issuedBy varchar(255) not null,
  number varchar(255) not null,
  address varchar(255) not null,
  city varchar(255) not null,
  date date not null,
  district varchar(255),
  region varchar(255) not null,
  series varchar(255) not null,
  primary key (id)
);

create table Inspection (
  id bigint generated by default as identity,
  date date not null,
  inspector varchar(255) not null,
  vehicle_id bigint not null,
  primary key (id)
);

create table VehiclePass (
  id bigint generated by default as identity,
  bodyColor varchar(255) not null,
  bodyNumber varchar(255),
  builtYear integer not null,
  category varchar(255) not null,
  chassisNumber varchar(255) not null,
  engineNumber varchar(255) not null,
  model varchar(255) not null,
  type varchar(255) not null,
  vin varchar(255) not null,
  primary key (id)
);

alter table Citizen
  add constraint UK6sat5p0fci5gnxc2ha40637b3 unique (series, number);

alter table VehiclePass
  add constraint UK_ld3vtmcjc5fmoj1i7rx70oybc unique (vin);

alter table Inspection
  add constraint FK807g9vo2jopk0kfofhlda1lse
  foreign key (vehicle_id)
  references VehiclePass;