//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 10:04:26 PM MSK 
//


package ru.vlsu.gibdd.webservice.common.io;

import java.io.Serializable;
import java.time.LocalDate;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for Citizen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Citizen">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="middlename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gender" type="{http://vlsu.ru/schema/citizen}Gender"/>
 *         &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="birth_place" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="passport" type="{http://vlsu.ru/schema/citizen}Passport"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Citizen", propOrder = {

})
public class CitizenIo
    extends AbstractIo
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected String firstname;
    @XmlElement(required = true, nillable = true)
    protected String middlename;
    @XmlElement(required = true)
    protected String lastname;
    @XmlElement(required = true)
    protected GenderIo gender;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "date")
    protected LocalDate birthday;
    @XmlElement(name = "birth_place", required = true)
    protected String birthPlace;
    @XmlElement(required = true)
    protected PassportIo passport;

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstname(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the middlename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddlename() {
        return middlename;
    }

    /**
     * Sets the value of the middlename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddlename(String value) {
        this.middlename = value;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastname(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link GenderIo }
     *     
     */
    public GenderIo getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderIo }
     *     
     */
    public void setGender(GenderIo value) {
        this.gender = value;
    }

    /**
     * Gets the value of the birthday property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getBirthday() {
        return birthday;
    }

    /**
     * Sets the value of the birthday property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthday(LocalDate value) {
        this.birthday = value;
    }

    /**
     * Gets the value of the birthPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthPlace(String value) {
        this.birthPlace = value;
    }

    /**
     * Gets the value of the passport property.
     * 
     * @return
     *     possible object is
     *     {@link PassportIo }
     *     
     */
    public PassportIo getPassport() {
        return passport;
    }

    /**
     * Sets the value of the passport property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassportIo }
     *     
     */
    public void setPassport(PassportIo value) {
        this.passport = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof CitizenIo)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CitizenIo that = ((CitizenIo) object);
        {
            String lhsFirstname;
            lhsFirstname = this.getFirstname();
            String rhsFirstname;
            rhsFirstname = that.getFirstname();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "firstname", lhsFirstname), LocatorUtils.property(thatLocator, "firstname", rhsFirstname), lhsFirstname, rhsFirstname)) {
                return false;
            }
        }
        {
            String lhsMiddlename;
            lhsMiddlename = this.getMiddlename();
            String rhsMiddlename;
            rhsMiddlename = that.getMiddlename();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "middlename", lhsMiddlename), LocatorUtils.property(thatLocator, "middlename", rhsMiddlename), lhsMiddlename, rhsMiddlename)) {
                return false;
            }
        }
        {
            String lhsLastname;
            lhsLastname = this.getLastname();
            String rhsLastname;
            rhsLastname = that.getLastname();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lastname", lhsLastname), LocatorUtils.property(thatLocator, "lastname", rhsLastname), lhsLastname, rhsLastname)) {
                return false;
            }
        }
        {
            GenderIo lhsGender;
            lhsGender = this.getGender();
            GenderIo rhsGender;
            rhsGender = that.getGender();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "gender", lhsGender), LocatorUtils.property(thatLocator, "gender", rhsGender), lhsGender, rhsGender)) {
                return false;
            }
        }
        {
            LocalDate lhsBirthday;
            lhsBirthday = this.getBirthday();
            LocalDate rhsBirthday;
            rhsBirthday = that.getBirthday();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "birthday", lhsBirthday), LocatorUtils.property(thatLocator, "birthday", rhsBirthday), lhsBirthday, rhsBirthday)) {
                return false;
            }
        }
        {
            String lhsBirthPlace;
            lhsBirthPlace = this.getBirthPlace();
            String rhsBirthPlace;
            rhsBirthPlace = that.getBirthPlace();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "birthPlace", lhsBirthPlace), LocatorUtils.property(thatLocator, "birthPlace", rhsBirthPlace), lhsBirthPlace, rhsBirthPlace)) {
                return false;
            }
        }
        {
            PassportIo lhsPassport;
            lhsPassport = this.getPassport();
            PassportIo rhsPassport;
            rhsPassport = that.getPassport();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "passport", lhsPassport), LocatorUtils.property(thatLocator, "passport", rhsPassport), lhsPassport, rhsPassport)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theFirstname;
            theFirstname = this.getFirstname();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "firstname", theFirstname), currentHashCode, theFirstname);
        }
        {
            String theMiddlename;
            theMiddlename = this.getMiddlename();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "middlename", theMiddlename), currentHashCode, theMiddlename);
        }
        {
            String theLastname;
            theLastname = this.getLastname();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lastname", theLastname), currentHashCode, theLastname);
        }
        {
            GenderIo theGender;
            theGender = this.getGender();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "gender", theGender), currentHashCode, theGender);
        }
        {
            LocalDate theBirthday;
            theBirthday = this.getBirthday();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "birthday", theBirthday), currentHashCode, theBirthday);
        }
        {
            String theBirthPlace;
            theBirthPlace = this.getBirthPlace();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "birthPlace", theBirthPlace), currentHashCode, theBirthPlace);
        }
        {
            PassportIo thePassport;
            thePassport = this.getPassport();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "passport", thePassport), currentHashCode, thePassport);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theFirstname;
            theFirstname = this.getFirstname();
            strategy.appendField(locator, this, "firstname", buffer, theFirstname);
        }
        {
            String theMiddlename;
            theMiddlename = this.getMiddlename();
            strategy.appendField(locator, this, "middlename", buffer, theMiddlename);
        }
        {
            String theLastname;
            theLastname = this.getLastname();
            strategy.appendField(locator, this, "lastname", buffer, theLastname);
        }
        {
            GenderIo theGender;
            theGender = this.getGender();
            strategy.appendField(locator, this, "gender", buffer, theGender);
        }
        {
            LocalDate theBirthday;
            theBirthday = this.getBirthday();
            strategy.appendField(locator, this, "birthday", buffer, theBirthday);
        }
        {
            String theBirthPlace;
            theBirthPlace = this.getBirthPlace();
            strategy.appendField(locator, this, "birthPlace", buffer, theBirthPlace);
        }
        {
            PassportIo thePassport;
            thePassport = this.getPassport();
            strategy.appendField(locator, this, "passport", buffer, thePassport);
        }
        return buffer;
    }

}
