//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 10:04:26 PM MSK 
//


package ru.vlsu.gibdd.webservice.common.io;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.vlsu.gibdd.webservice.common.io package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.vlsu.gibdd.webservice.common.io
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PassportIo }
     * 
     */
    public PassportIo createPassportIo() {
        return new PassportIo();
    }

    /**
     * Create an instance of {@link RegistrationIo }
     * 
     */
    public RegistrationIo createRegistrationIo() {
        return new RegistrationIo();
    }

    /**
     * Create an instance of {@link CitizenIo }
     * 
     */
    public CitizenIo createCitizenIo() {
        return new CitizenIo();
    }

    /**
     * Create an instance of {@link VehiclePassIo }
     * 
     */
    public VehiclePassIo createVehiclePassIo() {
        return new VehiclePassIo();
    }

}
