//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 10:04:26 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vlsu.ru/schema/citizen", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://vlsu.ru/schema/citizen", prefix = ""),
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://vlsu.ru/schema/vehicle", prefix = "")
})
package ru.vlsu.gibdd.webservice.common.io;
