//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 08:45:56 PM MSK 
//


package ru.vlsu.gibdd.webservice.signature.io;

import java.time.Year;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter2
    extends XmlAdapter<String, Year>
{


    public Year unmarshal(String value) {
        return (ru.vlsu.gibdd.webservice.common.util.DatatypeIoConverterUtils.parseXSDYear(value));
    }

    public String marshal(Year value) {
        return (ru.vlsu.gibdd.webservice.common.util.DatatypeIoConverterUtils.printXSDYear(value));
    }

}
