//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 08:45:56 PM MSK 
//


package ru.vlsu.gibdd.webservice.signature.io;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;
import ru.vlsu.gibdd.webservice.common.io.AbstractIo;
import ru.vlsu.gibdd.webservice.common.io.CitizenIo;
import ru.vlsu.gibdd.webservice.common.io.VehiclePassIo;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="citizen" type="{http://vlsu.ru/schema/citizen}Citizen"/>
 *         &lt;element name="vehicle" type="{http://vlsu.ru/schema/vehicle}VehiclePass"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "GenerateSignatureRequest")
public class GenerateSignatureRequestIo
    extends AbstractIo
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected CitizenIo citizen;
    @XmlElement(required = true)
    protected VehiclePassIo vehicle;

    /**
     * Gets the value of the citizen property.
     * 
     * @return
     *     possible object is
     *     {@link CitizenIo }
     *     
     */
    public CitizenIo getCitizen() {
        return citizen;
    }

    /**
     * Sets the value of the citizen property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitizenIo }
     *     
     */
    public void setCitizen(CitizenIo value) {
        this.citizen = value;
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * @return
     *     possible object is
     *     {@link VehiclePassIo }
     *     
     */
    public VehiclePassIo getVehicle() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehiclePassIo }
     *     
     */
    public void setVehicle(VehiclePassIo value) {
        this.vehicle = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof GenerateSignatureRequestIo)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final GenerateSignatureRequestIo that = ((GenerateSignatureRequestIo) object);
        {
            CitizenIo lhsCitizen;
            lhsCitizen = this.getCitizen();
            CitizenIo rhsCitizen;
            rhsCitizen = that.getCitizen();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "citizen", lhsCitizen), LocatorUtils.property(thatLocator, "citizen", rhsCitizen), lhsCitizen, rhsCitizen)) {
                return false;
            }
        }
        {
            VehiclePassIo lhsVehicle;
            lhsVehicle = this.getVehicle();
            VehiclePassIo rhsVehicle;
            rhsVehicle = that.getVehicle();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "vehicle", lhsVehicle), LocatorUtils.property(thatLocator, "vehicle", rhsVehicle), lhsVehicle, rhsVehicle)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            CitizenIo theCitizen;
            theCitizen = this.getCitizen();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "citizen", theCitizen), currentHashCode, theCitizen);
        }
        {
            VehiclePassIo theVehicle;
            theVehicle = this.getVehicle();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "vehicle", theVehicle), currentHashCode, theVehicle);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            CitizenIo theCitizen;
            theCitizen = this.getCitizen();
            strategy.appendField(locator, this, "citizen", buffer, theCitizen);
        }
        {
            VehiclePassIo theVehicle;
            theVehicle = this.getVehicle();
            strategy.appendField(locator, this, "vehicle", buffer, theVehicle);
        }
        return buffer;
    }

}
